### ISSUE TITLE
could not delete undefined element in an array

### ISSUE THREAD

**Issue by reverocean** [debitoor/dot-prop-immutable#14]
I want to delete an element in an array with index, but the element is undefined. After I call the `delete` method, it return the array which is not be deleted the undefined

```
const b = [1, 2, undefined, 3, 4]
dotProp.delete(b, 2) //will return [1, 2, undefined, 3, 4], rather than [1, 2, 3, 4]
```

**Comment by hilleer** [comment]
Should be resolved already in this pr: https://github.com/debitoor/dot-prop-immutable/commit/c6199bab1ef7c2d3d0b0ca57521926e4037ef57b.
