### ISSUE TITLE
Map keys with dots are interpreted as paths.

### ISSUE THREAD

**Issue by Flamenco** [debitoor/dot-prop-immutable#22]
I am trying to not use a property array for addressing a map with string/dot keys.
I am writing a patch to address this.  Please respond with your thoughts....

```json
const state = {
 "map" : { 
 "http://foo.bar" : 1,
 "http://me.you" : 2
 }
}
```
I can't address the keys with dots.

Solution #1 Use Brackets
```javascript
dotProp.set(state, "map['http://foo.bar']", 3)
```
Solution #2A Escape Dots With Backslash
```javascript
dotProp.set(state, "map.http://foo\\.bar", 3)
```
Solution #2B Escape Dots With Dot
```javascript
dotProp.set(state, "map.http://foo..bar", 3)
```
Solution #3 Use quotes/apostrophes
```javascript
dotProp.set(state, 'map."http://foo.bar"', 3)
```

**Comment by cluk3** [comment]
this commit https://github.com/debitoor/dot-prop-immutable/commit/9d5602e5978e76399286c353d974bbfac071d661 is already solving your issue, using the solution n2

**Comment by hilleer** [comment]
The commit @cluk3 suggested to have implemented this already does seem to have so.

@Flamenco please comment here if the implementation is in fact not a solution to your request.
