### ISSUE TITLE
Use number as a path

### ISSUE THREAD

**Issue by tai2** [debitoor/dot-prop-immutable#3]
```
dotProp.set({}, 0, 'a'); // Returns 'a' instead of {'0': 'a'}
```

This causes the result indifferent to my intention.
So I use toString() when path is a Number now.

I think it's very useful and consistent if I can use a number path.

**Comment by Flamenco** [comment]
see PR
https://github.com/debitoor/dot-prop-immutable/pulls

**Comment by tai2** [comment]
Nice work!

**Comment by hilleer** [comment]
Closing as this sound as resolved already.
