### ISSUE TITLE
Multiple '.' in attribute (e.g. dot.dot.dot) breaks

### ISSUE THREAD

**Issue by ckoning** [debitoor/dot-prop-immutable#36]
Indexing an object keyed by a hostname with subdomains (www.example.com) does not work, while a root level domain (example.com) does work. 

```
dotProp.get({foo: {'dot.dot': 'unicorn'}}, 'foo.dot\\.dot') //=> 'unicorn'
dotProp.get({foo: {'dot.dot.dot': 'unicorn'}}, 'foo.dot\\.dot\\.dot') //=> undefined
```

The [propToArray](https://github.com/debitoor/dot-prop-immutable/blob/master/lib/index.js#L154-L165) function is discarding its previous work after iteratively merging escaped path members:

```
ret.pop();
ret.push(last.slice(0, -1) + '.' + el);
```

Retaining the previous value and using it in the merge fixes the issue:

```
const prev = ret.pop();
ret.push(prev.slice(0, -1) + '.' + el);
```

Didn't seem worth the effort to fork the repo, make the fix, and submit a PR for a two line fix, so I'm submitting an issue with the path instead.

**Comment by hilleer** [comment]
Hi @ckoning ,

thanks for your contribution. 

@JonathanMH is working on implementing your suggestion and he/I will keep you updated.
