### ISSUE TITLE
Polyfill Object.assign if necessary

### ISSUE THREAD

**Issue by yaruson** [debitoor/dot-prop-immutable#8]
Unfortunately, Internet Explorer 11 doesn't support `Object.assign` method. As I can see, it might be [polyfilled with code from the MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).

I'd like to suggest use polyfill code when `Object.assign` is not available and native one in other case. I'll prepare corresponding pull request if the change will be considered acceptable.

**Comment by rodrigocnascimento** [comment]
Hi, I`m having the same problem trying to build an cordova app. I`m getting this error too. But I think the error is not a related issue, but It'll great if  this module have this feature.

**Comment by selfcontained** [comment]
I think it's generally better to leave things like polyfilling out of libraries like this, and let that fall into the application realm.  Adding the polyfills your app needs via something like [babel-polyfill](https://babeljs.io/docs/usage/polyfill/#usage-in-browser) or [es6-shim](https://github.com/paulmillr/es6-shim) are pretty common solutions.

Some disadvantages of having libraries adding polyfills is that it adds extra bloat where it sometimes isn't needed.  For example, if I use this library in node, I can expect things like `Object.assign` to exist, so any built in polyfill would be wasted.  If I'm using this in the browser, there's a high likelihood that I'm already adding polyfills via something like `babel-polyfill` for my app, so any polyfill in this library would be unwanted duplication increasing page weight.

**Comment by jonatanpedersen** [comment]
I agree with @selfcontained. Polyfilling should be left to the consumer of the library. I am closing this issue.
